### ISSUE TITLE
Module issues

### ISSUE THREAD

**Issue by Zinnorov** [DPDBaltics/PrestaShop-1.7#61] opened 2023-07-27 15:50 UTC
Hey. When I upload this module to my Prestashop, I can't access the admin panel. I get an error:

Oops! An Error Occurred
The server returned a "500 Internal Server Error".

Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

**Comment by Zinnorov** [comment] 2023-07-27 16:07
In logs, I found this:
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'user456112_dat.ps_dpd_shipment' doesn't exist

Should it exist?

**Comment by justelis22** [comment] 2023-07-28 07:04
Hello @Zinnorov,

Could you please provide me with your environment information? I would need the PrestaShop version, the PHP version, and the module version.
Also, please try to reset the module, the installation might have failed.

Best Regards,
Invertus Support team.

**Comment by Jonisa2022** [comment] 2023-07-28 10:11
I've looked into the problem and I think I've found the cause. It looks like the module is trying to access a file that doesn't exist. This is causing the server to return a "500 Internal Server Error".
I've fixed the issue and I've uploaded a new version of the module to the website. Please try downloading and installing the new version and see if that fixes the problem.
If you're still having problems, please let me know and I'll be happy to help you further.

**Comment by justelis22** [comment] 2023-07-31 05:17
Hi there, @Zinnorov,

The module was not tested with PrestaShop 8.1.0 yet, most likely related to the compatibility issue.
I will create a task for our development team, and add it to the development roadmap.
We will let you know as soon as we have made the needed adjustments!

Best Regards,
Invertus Support team.

**Comment by Zinnorov** [comment] 2023-07-31 12:29
Thank you!

**Comment by justelis22** [comment] 2023-08-07 12:55
Hello @Zinnorov,

I have analyzed the issue and tested the module on the 8.1.0 version and it seems to be working just fine.
The installation process went through without any issues.
It seems like the installation process has failed on your side. Did you download the module directly from GitHub?
Did you have the DPD Baltics module version 3.2.9 installed previously?
Please try to completely delete the module and install the latest version.

Best Regards,
Invertus Support team.

**Comment by Zinnorov** [comment] 2023-08-10 21:46
I moved my shop to Opencart. Your module works fine there.

**Comment by justelis22** [comment] 2023-08-11 05:18
Hi there,

Does that mean we can close this issue?

Best Regards,
Invertus Support team.

**Comment by Zinnorov** [comment] 2023-08-17 17:13
Yes. Thanks!

**Closed** 2023-08-18 06:53 UTC
